name: CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '47 6 * * *'

jobs:
  pre-commit-checks:
    name: "Lint using pre-commit"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0

  tests:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    strategy:
      fail-fast: false
      matrix:
        target:
          - +test-python3.8-arrow1.x.x
          - +test-python3.8-arrow2.x.x
          - +test-python3.8-arrow3.x.x
          - +test-python3.8-arrow4.x.x
          - +test-python3.8-arrow5.x.x
          - +test-python3.8-arrow6.x.x
          - +test-python3.8-arrow7.x.x
          - +test-python3.8-arrow8.x.x
          - +test-python3.9-arrow1.x.x
          - +test-python3.9-arrow2.x.x
          - +test-python3.9-arrow3.x.x
          - +test-python3.9-arrow4.x.x
          - +test-python3.9-arrow5.x.x
          - +test-python3.9-arrow6.x.x
          - +test-python3.9-arrow7.x.x
          - +test-python3.9-arrow8.x.x
          - +test-python3.10-arrow1.x.x
          - +test-python3.10-arrow2.x.x
          - +test-python3.10-arrow3.x.x
          - +test-python3.10-arrow4.x.x
          - +test-python3.10-arrow5.x.x
          - +test-python3.10-arrow6.x.x
          - +test-python3.10-arrow7.x.x
          - +test-python3.10-arrow8.x.x
        experimental: [ false ]
        upload: [ false ]
        include:
          - target: +test-python3.8-arrow8.x.x
            experimental: false
            upload: true
          - target: +test-python3.9-arrow8.x.x
            experimental: false
            upload: true
          - target: +test-python3.10-arrow8.x.x
            experimental: false
            upload: true
          - target: +test-python3.8-arrow-nightly
            experimental: true
            upload: false
          - target: +test-python3.9-arrow-nightly
            experimental: true
            upload: false
          - target: +test-python3.10-arrow-nightly
            experimental: true
            upload: false
    steps:
      - uses: actions/checkout@v2
      - name: Download earthly 0.5.0
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.0/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Run build
        run: earthly --allow-privileged ${{ matrix.target }}
        continue-on-error: ${{ matrix.experimental }}

      - name: Upload coverage for Python
        if: ${{ matrix.upload }}
        uses: codecov/codecov-action@v1
        with:
          files: result/cov/python/python_cov.xml
          fail_ci_if_error: true
          verbose: true
          functionalities: gcov
      - name: Upload coverage for C++
        if: ${{ matrix.upload }}
        uses: codecov/codecov-action@v1
        with:
          directory: result/cov/cpp
          fail_ci_if_error: true
          verbose: true
          functionalities: coveragepy, gcov

      - name: Publish package
        if: matrix.upload && github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.repository == 'blue-yonder/turbodbc'

        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOAD }}
          packages_dir: result/dist
